services:
  postgres:
    container-name: postgres
    image: postgres
    environment:
      POSTGRES_USER: larrycode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
      PG_ADMIN_CONFIG_SERVER_MODE: 'False'
    Volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      -postgres
    restart: unless-stopped

  networks:
    postgres:
      driver: bridge